### ISSUE TITLE
error: equihash-solomining/lib/stratum/pool.js:579                        

### ISSUE THREAD

**Issue by stam75** [aayanl/equihash-solomining#15]
The  pool throws an error while running. I am connecting to the pool using miner.exe (EBWF miner).

1. I am able to mine on Zcash node
2. Able to connect to zcash node
3. Expect this error pool appears to be working

Thanks for all your help.

[2017/12/27 22:42:09] getblocktemplate call failed for daemon instance 0 with error {"type":"request error","message":"socket hang up"}
[PoolWorker][Thread 0][2017/12/27 22:42:09] Block notification via RPC polling
/home/**user**/Zcash/equihash-solomining/lib/stratum/pool.js:579
                        result.response.miner = subsidy.miner;
                                                        ^

TypeError: Cannot read property 'miner' of undefined
    at /home/**user**/Zcash/equihash-solomining/lib/stratum/pool.js:579:57
    at itemFinished (/home/**user**/Zcash/equihash-solomining/lib/stratum/daemon.js:155:36)
    at /home/**user**/Zcash/equihash-solomining/lib/stratum/daemon.js:169:17
    at parseJson (/home/**user**/Zcash/equihash-solomining/lib/stratum/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/stam2040/Zcash/equihash-solomining/lib/stratum/daemon.js:95:17)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[Pool][Thread 10][2017/12/27 22:42:09] Fork 10 died, spawning replacement worker...
[PoolWorker][Thread 10][2017/12/27 22:42:12] Stratum Pool Server Started for zcash [ZEC] {equihash}

**Comment by TheComputerGenie** [comment]
"socket hang up" = you have no connection to the daemon
when you have no connection to the daemon, you can't get the subsidy data from the daemon
when you can get the subsidy data from the daemon, the subsidy data is "undefined"
